CREATE TABLE code (
                      code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      created_at TIMESTAMP,
                      updated_at TIMESTAMP,
                      code VARCHAR(255) NOT NULL,
                      group_code VARCHAR(255) NOT NULL,
                      name VARCHAR(255) NOT NULL,
                      UNIQUE (group_code, code)
);

CREATE TABLE member_info (
                             member_info_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             created_at TIMESTAMP,
                             updated_at TIMESTAMP,
                             birth VARCHAR(255) NOT NULL,
                             email VARCHAR(255) NOT NULL,
                             password VARCHAR(255) NOT NULL
);

CREATE TABLE vacation_info (
                               vacation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               total_count DOUBLE NOT NULL,
                               use_count DOUBLE NOT NULL,
                               version INT NOT NULL,
                               created_at TIMESTAMP,
                               updated_at TIMESTAMP,
                               vacation_type VARCHAR(255),
                               member_id BIGINT
);

CREATE TABLE vacation_info_log (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   total_count DOUBLE NOT NULL,
                                   use_count DOUBLE NOT NULL,
                                   log_date TIMESTAMP,
                                   vacation_type VARCHAR(255),
                                   member_id BIGINT
);

CREATE TABLE members (
                         member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_at TIMESTAMP,
                         updated_at TIMESTAMP,
                         join_date TIMESTAMP NOT NULL,
                         name VARCHAR(255) NOT NULL,
                         role VARCHAR(50) NOT NULL,
                         dept_id BIGINT,
                         member_info_id BIGINT,
                         position_id BIGINT,
                         UNIQUE (member_info_id)
);

CREATE TABLE dept (
                      dept_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      created_at TIMESTAMP,
                      updated_at TIMESTAMP,
                      dept_name VARCHAR(255) NOT NULL,
                      dept_leader_id BIGINT,
                      UNIQUE (dept_leader_id)
);

CREATE TABLE vacation_request (
                                  vacation_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  version INT,
                                  created_at TIMESTAMP,
                                  updated_at TIMESTAMP,
                                  from_date TIMESTAMP NOT NULL,
                                  to_date TIMESTAMP NOT NULL,
                                  reason VARCHAR(255),
                                  status VARCHAR(50),
                                  type_code BIGINT,
                                  member_id BIGINT
);

CREATE TABLE approval_step (
                               approval_step_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               created_at TIMESTAMP,
                               updated_at TIMESTAMP,
                               reason VARCHAR(255),
                               approval_status VARCHAR(50) NOT NULL,
                               step INT NOT NULL,
                               member_id BIGINT NOT NULL,
                               vacation_request_id BIGINT NOT NULL
);


ALTER TABLE members ADD CONSTRAINT fk_member_info FOREIGN KEY (member_info_id) REFERENCES member_info(member_info_id);
ALTER TABLE members ADD CONSTRAINT fk_dept FOREIGN KEY (dept_id) REFERENCES dept(dept_id);
ALTER TABLE members ADD CONSTRAINT fk_position FOREIGN KEY (position_id) REFERENCES code(code_id);

ALTER TABLE dept ADD CONSTRAINT fk_dept_leader FOREIGN KEY (dept_leader_id) REFERENCES members(member_id);

ALTER TABLE vacation_request ADD CONSTRAINT fk_vacation_type FOREIGN KEY (type_code) REFERENCES code(code_id);
ALTER TABLE vacation_request ADD CONSTRAINT fk_vacation_member FOREIGN KEY (member_id) REFERENCES members(member_id);

ALTER TABLE approval_step ADD CONSTRAINT fk_approval_member FOREIGN KEY (member_id) REFERENCES members(member_id);
ALTER TABLE approval_step ADD CONSTRAINT fk_approval_request FOREIGN KEY (vacation_request_id) REFERENCES vacation_request(vacation_request_id);
